name: Continuous Delivery

on:
  push:
    branches:
      - master

# default: least privileged permissions across all jobs
permissions:
  contents: read


env:
  SEMANTIC_RELEASE_CONFIG_FILE: "./semantic-release.toml"
  PACKAGE_NAME: "psr-demo"
  DISTRIBUTION_FILE_INCIPIT: "psr_demo"
  TEST_DEPENDENCY_GROUP: "test"
  RUN_TEST_COMMAND: "uv run -- pytest --verbose"
  DISTRIBUTION_ARTIFACTS_NAME: "dist"
  DISTRIBUTION_ARTIFACTS_DIR: "dist"
  LOCK_FILE_ARTIFACT: "uv.lock"


  build:
    name: Build
    needs: variables
    uses: ./.github/workflows/build.yml
    with:
      semantic-release-config-file: ${{ env.SEMANTIC_RELEASE_CONFIG_FILE }}
      distribution-artifacts-name: ${{ env.DISTRIBUTION_ARTIFACTS_NAME }}
      distribution-artifacts-dir: ${{ env.DISTRIBUTION_ARTIFACTS_DIR }}
      lock-file-artifact: ${{ env.LOCK_FILE_ARTIFACT }}


  test-e2e:
    needs: build
    uses: ./.github/workflows/e2e-test.yml
    with:
      new-release-detected: ${{ needs.build.outputs.new-release-detected }}
      artifacts-name: ${{ needs.build.outputs.distribution-artifacts-name }}
      artifacts-dir: ${{ needs.build.outputs.distribution-artifacts-dir }}
      package-name: ${{ env.PACKAGE_NAME }}
      distribution-file-incipit: ${{ env.DISTRIBUTION_FILE_INCIPIT }}
      test-dependency-group: ${{ env.TEST_DEPENDENCY_GROUP }} 
      run-test-command: ${{ env.RUN_TEST_COMMAND }}


  release:
    needs:
      - variables
      - build
      - test-e2e
    uses: ./.github/workflows/release.yml
    with:
      new-release-detected: ${{ needs.build.outputs.new-release-detected }}
      semantic-release-config-file: ${{ needs.variables.outputs.semantic-release-config-file }}
      distribution-artifacts-name: ${{ needs.build.outputs.distribution-artifacts-name }}
      distribution-artifacts-dir: ${{ needs.build.outputs.distribution-artifacts-dir }}
      lock-file-artifact: ${{ needs.build.outputs.lock-file-artifact }}
    secrets: inherit
    permissions:
      contents: write


  publish:
    needs:
      - variables
      - release
    uses: ./.github/workflows/publish.yml
    with:
      package-name: ${{ needs.variables.outputs.package-name }}
