name: Continuous Delivery

on:
  push:
    branches:
      - master

permissions:
  contents: read


env:
  # Configurable by user
  SEMANTIC_RELEASE_CONFIG_FILE: "./semantic-release.toml"
  PACKAGE_NAME: "psr-demo"
  DISTRIBUTION_FILE_INCIPIT: "psr_demo"
  TEST_DEPENDENCY_GROUP: "test"
  RUN_TEST_COMMAND: "uv run -- pytest --verbose"
  # Not configurable by user
  DISTRIBUTION_ARTIFACTS_NAME: "dist"
  DISTRIBUTION_ARTIFACTS_DIR: "dist"
  LOCK_FILE_ARTIFACT: "uv.lock"


jobs:
  build:
    name: Build
    needs: variables
    uses: ./.github/workflows/build.yml
    with:
      semantic-release-config-file: ${{ env.SEMANTIC_RELEASE_CONFIG_FILE }}
      distribution-artifacts-name: ${{ env.DISTRIBUTION_ARTIFACTS_NAME }}
      distribution-artifacts-dir: ${{ env.DISTRIBUTION_ARTIFACTS_DIR }}
      lock-file-artifact: ${{ env.LOCK_FILE_ARTIFACT }}


  test-e2e:
    name: End-to-End Test
    needs: build
    uses: ./.github/workflows/e2e-test.yml
    with:
      new-release-detected: ${{ needs.build.outputs.new-release-detected }}
      distribution-artifacts-name: ${{ env.DISTRIBUTION_ARTIFACTS-NAME }}
      distribution-artifacts-dir: ${{ env.DISTRIBUTION_ARTIFACTS-DIR }}
      package-name: ${{ env.PACKAGE_NAME }}
      distribution-file-incipit: ${{ env.DISTRIBUTION_FILE_INCIPIT }}
      test-dependency-group: ${{ env.TEST_DEPENDENCY_GROUP }} 
      run-test-command: ${{ env.RUN_TEST_COMMAND }}


  release:
    name: Release
    needs:
      - variables
      - build
      - test-e2e
    uses: ./.github/workflows/release.yml
    with:
      new-release-detected: ${{ needs.build.outputs.new-release-detected }}
      semantic-release-config-file: ${{ env.SEMANTIC_RELEASE_CONFIG_FILE }}
      distribution-artifacts-name: ${{ env.DISTRIBUTION_ARTIFACTS_NAME }}
      distribution-artifacts-dir: ${{ env.DISTRIBUTION_ARTIFACTS_DIR }}
      lock-file-artifact: ${{ env.LOCK_FILE_ARTIFACT }}
    secrets: inherit
    permissions:
      contents: write


  publish:
    name: Publish
    needs:
      - variables
      - release
    uses: ./.github/workflows/publish.yml
    with:
      new-version-released: ${{ needs.release.outputs.new-version-released }}
      package-name: ${{ env.PACKAGE_NAME }}
      distribution-artifacts-name: ${{ env.DISTRIBUTION_ARTIFACTS_NAME }}
      distribution-artifacts-dir: ${{ env.DISTRIBUTION_ARTIFACTS_DIR }}
