name: Publish

on:
  workflow_call:
    inputs:
      new-version-released:
        required: true
        type: string
      package-name:
        required: true
        type: string
      distribution-artifacts-name:
        required: true
        type: string
      distribution-artifacts-dir:
        required: true
        type: string


jobs:
  publish-on-testpypi:
    name: Publish on TestPyPI
    needs: release
    runs-on: ubuntu-latest

    if: ${{ inputs.new-version-released == 'true' }}

    environment:
      name: testpypi
      url: https://test.pypi.org/p/${{ inputs.package-name }}

    permissions:
      contents: read  # check if this is redundant
      id-token: write

    steps:
      - name: Setup | Download Build Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5.0.0
        id: artifact-download
        with:
          name: ${{ inputs.distribution-artifacts-name }}
          path: ${{ inputs.distribution-artifacts-dir }}

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          packages-dir: ${{ inputs.distribution-artifacts-dir }}
          print-hash: true
          verbose: true
          repository-url: https://test.pypi.org/legacy/


  publish-on-pypi:
    name: Publish on PyPI
    needs: release
    runs-on: ubuntu-latest

    if: ${{ inputs.new-version-released == 'true' }}

    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.package-name }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup | Download Build Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5.0.0
        id: artifact-download
        with:
          name: ${{ inputs.distribution-artifacts-name }}
          path: ${{ inputs.distribution-artifacts-dir }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          packages-dir: ${{ inputs.distribution-artifacts-dir }}
          print-hash: true
          verbose: true

